"use client";

import PrintReportButton from "../../components/PrintReportButton";

export default function ReportPage() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-16">
      <div className="rounded-xl border bg-white p-10 print:border-0">
        <h1 className="text-3xl font-bold">CBAM Assessment Report</h1>
        <p className="mt-2 text-gray-500">Generated by CBAMtools.com</p>

        <div className="mt-8 space-y-4">
          <div><strong>Company:</strong> __________________</div>
          <div><strong>Product:</strong> __________________</div>
          <div><strong>HS Code:</strong> __________________</div>
          <div><strong>Quantity:</strong> __________________</div>
          <div><strong>Estimated Emission:</strong> __________________</div>
          <div><strong>Estimated CBAM Cost:</strong> __________________</div>
        </div>

        <div className="mt-10 text-sm text-gray-500">
          This calculation is provided for reference purposes only. Actual CBAM obligations depend on official regulatory requirements and verified emission data.
        </div>

        <div className="mt-8 print:hidden">
          <PrintReportButton />
        </div>
      </div>
    </main>
  );
}
