export interface CBAMReportData {
  company?: string;
  product?: string;
  hsCode?: string;
  quantity?: string;
  emission?: string;
  cost?: string;
}

export function createCBAMReportText(data: CBAMReportData) {
  return `CBAM Assessment Report

Company: ${data.company || "-"}
Product: ${data.product || "-"}
HS Code: ${data.hsCode || "-"}
Quantity: ${data.quantity || "-"}
Estimated Emission: ${data.emission || "-"}
Estimated CBAM Cost: ${data.cost || "-"}

Generated by CBAMtools.com
This assessment is for reference purposes only.`;
}
