export interface PDFReportData {
  company?: string;
  product?: string;
  hsCode?: string;
  quantity?: string;
  emission?: string;
  cost?: string;
}

export function buildPDFReportContent(data: PDFReportData) {
  return {
    title: "CBAM Assessment Report",
    sections: [
      `Company: ${data.company || "-"}`,
      `Product: ${data.product || "-"}`,
      `HS Code: ${data.hsCode || "-"}`,
      `Quantity: ${data.quantity || "-"}`,
      `Estimated Emission: ${data.emission || "-"}`,
      `Estimated CBAM Cost: ${data.cost || "-"}`,
    ],
    footer: "Generated by CBAMtools.com. This assessment is for reference only.",
  };
}
