"use client";
import {Suspense,useMemo,useState} from "react";
import {useSearchParams} from "next/navigation";
const sectors=["Iron & Steel","Aluminium","Cement","Fertilisers","Hydrogen","Electricity"];
const commonOrigins=["China","India","Türkiye","United Kingdom","United States","South Korea","Japan","Vietnam","United Arab Emirates","South Africa","Brazil","Other / enter manually"];const fmt=new Intl.NumberFormat("en-IE",{maximumFractionDigits:2});
export default function CBAMCalculator(){return <Suspense fallback={<main className="calc-page"><section className="calc-hero"><div><span className="kicker">CBAM CALCULATOR</span><h1>Preparing calculator…</h1></div></section></main>}><CalculatorContent/></Suspense>}
function CalculatorContent(){const params=useSearchParams();const initialSector=params.get("sector")||"Iron & Steel",initialCode=params.get("code")||"";const [advanced,setAdvanced]=useState(false),[sector,setSector]=useState(initialSector),[code,setCode]=useState(initialCode),[country,setCountry]=useState(params.get("country")||""),[customOrigin,setCustomOrigin]=useState(false),[quantity,setQuantity]=useState("100"),[emission,setEmission]=useState(params.get("emissions")||"2"),[price,setPrice]=useState("75.28"),[benchmark,setBenchmark]=useState(""),[factor,setFactor]=useState("97.5"),[paid,setPaid]=useState(""),[emissionSource]=useState(params.get("emissions")?"EU default value":"Manual input");
const r=useMemo(()=>{const q=Math.max(0,Number(quantity)||0),e=Math.max(0,Number(emission)||0),p=Math.max(0,Number(price)||0),b=Math.max(0,Number(benchmark)||0),f=Math.min(100,Math.max(0,Number(factor)||0))/100,cp=Math.max(0,Number(paid)||0);const gross=q*e,free=q*b*f,adjusted=Math.max(0,gross-free),cost=Math.max(0,adjusted*p-Math.min(adjusted*p,gross*cp)),cert=p>0?cost/p:0;return{gross,free,adjusted,cost,cert}},[quantity,emission,price,benchmark,factor,paid]);
return <main className="calc-page"><aside className="result-panel"><span className="result-status">LIVE ESTIMATE</span><p>{sector}{code?" · "+code:""}{country?" · "+country:""}</p><div className="big-result"><small>ESTIMATED CBAM COST</small><strong>€{fmt.format(r.cost)}</strong><span>{emissionSource}</span></div><div className="result-row"><span>Embedded emissions</span><b>{fmt.format(r.gross)} tCO₂e</b></div><div className="result-row total"><span>Estimated certificates</span><b>{fmt.format(r.cert)}</b></div></aside></main>}
