export default function CBAMReportTemplate({
  product = "",
  hsCode = "",
  quantity = "",
  cost = "",
}) {
  return (
    <div className="rounded-xl border p-6 bg-white">
      <h2 className="text-2xl font-bold">CBAM Assessment Report</h2>
      <div className="mt-4 space-y-2 text-gray-700">
        <p>Product: {product || "Not provided"}</p>
        <p>HS Code: {hsCode || "Not provided"}</p>
        <p>Quantity: {quantity || "Not provided"}</p>
        <p>Estimated CBAM Cost: {cost || "Not calculated"}</p>
      </div>
      <p className="mt-6 text-sm text-gray-500">
        Generated by CBAMtools.com. This assessment is for reference purposes only.
      </p>
    </div>
  );
}
