"use client";

export default function PDFReportButton() {
  function generateReport() {
    const content = `CBAM Assessment Report\n\nGenerated by CBAMtools.com\n\nThis report is for reference only.`;
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "CBAM_Assessment_Report.txt";
    link.click();
    URL.revokeObjectURL(url);
  }

  return (
    <button
      onClick={generateReport}
      className="rounded bg-green-600 px-5 py-3 text-white"
    >
      Generate CBAM Report
    </button>
  );
}
